### ISSUE TITLE
Top demo doesn't work on Mobile Safari and Mobile Chrome

### ISSUE THREAD

**Issue by kjur** [PeculiarVentures/xadesjs#29] opened 2016-05-29 23:17 UTC
Hello. Top page demo (https://xadesjs.com/) doesn't seem to work on Mobile Safari(iOS 9.3.2 latest) and Mobile Chrome (50.0.2661.95 latest on iOS) as though WebCrypto signing and validation are supprted on them. Regards.

**Comment by rmhrisk** [comment] 2016-05-30 02:12
Close as dupe of https://github.com/PeculiarVentures/xadesjs/issues/27

**Closed by rmhrisk** 2016-05-30 02:12 UTC
