### ISSUE TITLE
error in node-webcrypto-ossl installation

### ISSUE THREAD

**Issue by kjur** [PeculiarVentures/xadesjs#18] opened 2016-05-07 00:08 UTC
As xadesjs npm page (https://www.npmjs.com/package/xadesjs) node-webcrypto-ossl installation as following: 
```
npm install node-webcrypto-ossl
```
However this seems to raise error. My error log is following:
```
sudo npm install -g node-webcrypto-ossl
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
/
> node-webcrypto-ossl@1.0.0 install /opt/local/lib/node_modules/node-webcrypto-ossl
> tsd install && tsc && node-gyp rebuild

sh: tsd: command not found
npm ERR! Darwin 14.5.0
npm ERR! argv "/opt/local/bin/node" "/opt/local/bin/npm" "install" "-g" "node-webcrypto-ossl"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! node-webcrypto-ossl@1.0.0 install: `tsd install && tsc && node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the node-webcrypto-ossl@1.0.0 install script 'tsd install && tsc && node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-webcrypto-ossl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsd install && tsc && node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-webcrypto-ossl
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls node-webcrypto-ossl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user1/z/npm-debug.log
```

As node-webcrypto-ossl npm page (https://www.npmjs.com/package/node-webcrypto-ossl), installation described as following:
```
git clone https://github.com/PeculiarVentures/node-webcrypto-ossl
cd node-webcrypto-ossl
npm install node-gyp -g
npm install typescript -g
npm install tsd -g
npm install mocha -g
npm install
tsd install
tsc
node-gyp configure build
```

How can I install node-webcrypto-ossl properly?

Thanks

**Comment by rmhrisk** [comment] 2016-05-07 00:10
It seems that tsd is not installed:

Can you double check if https://www.npmjs.com/package/tsd is installed?

**Comment by rmhrisk** [comment] 2016-05-07 00:12
I published a new node-webcrypto-ossl yesterday and I didnt test it seems (sorry): please do :

**Comment by rmhrisk** [comment] 2016-05-07 00:25
@kjur closing this issue, please open a new one in the node-webcrypto-ossl repository as the issue is there. I will see about fixing the npm package but for now you can install as per above.

**Comment by kjur** [comment] 2016-05-07 00:26
Thank you for letting me know. I'll try it.

**Closed by rmhrisk** 2016-05-07 00:25 UTC

**Comment by rmhrisk** [comment] 2016-05-07 00:30
Sorry for the mistake, I was careless.

**Comment by kjur** [comment] 2016-05-07 00:31
No problem.  :)

**Comment by kjur** [comment] 2016-05-07 00:38
I've tryed to install node-webcrypto-ossl and successfully done. Then I tried to run following "t1.js" however I got error. It seems that node-webcrypto-ossl was not installed properly.

``` JavaScript
// t1.js
var xadesjs = require("xadesjs");
var WebCrypto = require("node-webcrypto-ossl").default;
xadesjs.Application.setEngine("OpenSSL", new WebCrypto());
```

```
% node t1.js
```

Then I got following error:

```
$ node t1.js
module.js:327
    throw err;
    ^

Error: Cannot find module 'node-webcrypto-ossl'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/user1/z2/node-webcrypto-ossl/t1.js:2:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

Is there any solution?

**Comment by rmhrisk** [comment] 2016-05-07 00:40
It is hard to say without looking but you will probably have to specify the directory location in your require

**Comment by rmhrisk** [comment] 2016-05-07 01:12
Was that it?

**Comment by kjur** [comment] 2016-05-07 09:31
I've tried node-webcrypt-ossl installation as described above on Mac OS X and Ubuntu which is clean install environment however it can't be installed properly :(

**Comment by rmhrisk** [comment] 2016-05-07 21:13
The error you got suggests that the require doesnt point at the actual location of where you built node-webcrypto-ossl, did you double check that?

**Comment by kjur** [comment] 2016-05-08 02:57
Thank you for your advice. I did following installation procedure:

```
ENVIRONMNET:
  Ubuntu 14.04.3-32LTS on Mac OSX VirtualBox (almost clean installed)

SETUP PREREQUESTIES
  root% apt-get update
  root% aptitude install g++
  root% aptitude install npm
  root% ln -s /usr/bin/nodejs /usr/bin/node
  root% node -v >>> v0.10.25
  root% npm -v >>> 1.3.10

SETUP node-webcrypto-ossl
  root% mkdir ~/tmp1
  root% cd ~/tmp1
  root% git clone https://github.com/PeculiarVentures/node-webcrypto-ossl
  root% cd node-webcrypto-ossl
  root% npm install node-gyp -g
  root% npm install typescript -g
  root% npm install tsd -g
  root% npm install mocha -g
  root% npm install
  root% tsd install
  root% tsc

  # above are succressfully done. Then...

  root% node-gyp configure build

  # got many error such like:
  ../src/node/../core/scoped_ssl.h:32:20: error: 'nullptr' was not declared in this scope
    :
  ../src/node/../ec/ec_dsa.h:7:27: error: 'ScopedEVP_PKEY' was not declared in this scope
    :
```

**Comment by rmhrisk** [comment] 2016-05-08 06:53
It seems maybe you do not have OpenSSL and we assumed it was there, I will spin up a VM tomorrow to try in a similar config.

**Comment by kjur** [comment] 2016-05-08 07:28
Thanks. I've missed to install OpenSSL development package and tried again with adding following in prerequesties phase:
```
root% aptitude install libssl-dev
```
However it raise the same error as before. Thank you for your help.

**Comment by rmhrisk** [comment] 2016-05-09 21:37
@kjur please try the update npm module : https://www.npmjs.com/package/node-webcrypto-ossl it was built on ubuntu.

**Comment by kjur** [comment] 2016-05-10 00:41
Hello @rmhrisk . Thank you for the update. I'll try it later and let you know the result.

**Comment by kjur** [comment] 2016-05-10 14:38
Hello @rmhrisk . I have a question. How can I install it? The same procedure as described above? Otherwise just install npm package?
```
root% npm install node-webcrypto-ossl -g
```

**Comment by rmhrisk** [comment] 2016-05-10 19:41
We did not try as a global dependency, just as a local one : 

```
npm install node-webcrypto-ossl
```

**Comment by kjur** [comment] 2016-05-13 13:40
Hmm, I've tried it today again but still not works and causes the same error.

**Comment by microshine** [comment] 2016-05-13 17:19
Could you send a `npm-debug.log` file?
